// apps/vue-layers/src/components/GridDemo.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import * as FabricLayers from 'fabric-layers-core'

// State for controls
const minZoom = ref(0.05)
const maxZoom = ref(20)
const coordinates = ref({ x: 0, y: 0 })
const zoomLevel = ref(1.00)
let map: any = null

// Container ref
const canvasContainer = ref(null)

// Methods
const resetView = () => {
  if (map && typeof map.reset === 'function') map.reset()
}

const updateZoomLimits = () => {
  if (!map) return

  let min = parseFloat(minZoom.value.toString())
  let max = parseFloat(maxZoom.value.toString())
  
  if (isNaN(min) || min <= 0) min = 0.01
  if (isNaN(max) || max <= min) max = min + 0.01
  
  map.minZoom = min
  map.maxZoom = max
  
  // Clamp current zoom if needed
  if (map.zoom < min) map.setZoom(min)
  if (map.zoom > max) map.setZoom(max)
}

const updateZoomDisplay = () => {
  if (!map) return
  const zoom = map.zoom || 1
  zoomLevel.value = zoom
}

// Setup map when component mounts
onMounted(() => {
  console.log('FabricLayers version:', FabricLayers.version)

  // Create the map with grid enabled
  map = new FabricLayers.Map(canvasContainer.value, {
    width: 800,
    height: 600,
    showGrid: true,
    mode: 'GRAB', // Enable pan/zoom mode by default
  })

  // Show grid if not auto-enabled
  if (!map.grid) {
    if (typeof map.addGrid === 'function') map.addGrid()
  }

  // Event handlers
  map.on('mouse:move', (e: any) => {
    if (e && e.pointer) {
      coordinates.value = {
        x: parseFloat(e.pointer.x.toFixed(1)),
        y: parseFloat(e.pointer.y.toFixed(1))
      }
    }
  })

  map.on('mouse:out', () => {
    coordinates.value = { x: 0, y: 0 }
  })

  // Update zoom display
  map.on('update', updateZoomDisplay)
  updateZoomDisplay()

  // Debug events
  map.on('mouse:down', (e: any) => {
    if (e && e.pointer) {
      console.log('mouse:down', e.pointer)
    }
  })

  map.on('mouse:up', (e: any) => {
    if (e && e.pointer) {
      console.log('mouse:up', e.pointer)
    }
  })

  map.on('mouse:dblclick', (e: any) => {
    if (e && e.pointer) {
      console.log('mouse:dblclick', e.pointer)
    }
  })

  // Set initial zoom limits
  updateZoomLimits()
})
</script>

<template>
  <div>
    <h1>fabric-layers Grid Demo</h1>
    <div class="controls">
      <label style="margin-right:10px;">
        Min Zoom: <input type="number" step="0.01" v-model="minZoom" @change="updateZoomLimits" style="width:70px;">
      </label>
      <label style="margin-right:10px;">
        Max Zoom: <input type="number" step="0.01" v-model="maxZoom" @change="updateZoomLimits" style="width:70px;">
      </label>
      <button @click="resetView">Reset View</button>
      <span class="coordinates">X: {{ coordinates.x }}, Y: {{ coordinates.y }}</span>
      <span class="zoom-level">Zoom: {{ zoomLevel.toFixed(2) }}x</span>
    </div>
    <div ref="canvasContainer" class="canvas-container"></div>
  </div>
</template>

<style scoped>
.controls {
  margin: 20px 0;
  padding: 15px;
  background: #f5f5f5;
  border-radius: 4px;
}

button {
  padding: 8px 16px;
  margin-right: 10px;
  cursor: pointer;
}

.coordinates, .zoom-level {
  margin-left: 20px;
  font-family: monospace;
}

.canvas-container {
  border: 1px solid #ccc;
  margin: 20px 0;
  width: 800px;
  height: 600px;
  background: #f8f9fa;
}
</style>

// packages/fabric-layers-react/src/components/demo/GridDemo.tsx
import React, { useState, useCallback } from 'react';
import { Map } from '../Map';
import { Grid } from '../Map/Grid';
import styled from '@emotion/styled';

const DemoContainer = styled.div`
  margin: 0;
  padding: 20px;
  font-family: Arial, sans-serif;
`;

const CanvasContainer = styled.div`
  border: 1px solid #ccc;
  margin: 20px 0;
  width: 800px;
  height: 600px;
  background: #f8f9fa;
`;

const Controls = styled.div`
  margin: 20px 0;
  padding: 15px;
  background: #f5f5f5;
  border-radius: 4px;
`;

const Button = styled.button`
  padding: 8px 16px;
  margin-right: 10px;
  cursor: pointer;
`;

const Label = styled.label`
  margin-right: 10px;
`;

const Input = styled.input`
  width: 70px;
`;

const MonospaceText = styled.span`
  font-family: monospace;
  margin-left: 20px;
`;

export const GridDemo: React.FC = () => {
  const [coordinates, setCoordinates] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const [minZoom, setMinZoom] = useState(0.05);
  const [maxZoom, setMaxZoom] = useState(20);
  const [mapInstance, setMapInstance] = useState<any>(null);

  const handleMapReady = useCallback((map: any) => {
    setMapInstance(map);

    map.on('mouse:move', (e: any) => {
      if (e && e.pointer) {
        setCoordinates({
          x: e.pointer.x,
          y: e.pointer.y
        });
      }
    });

    map.on('mouse:out', () => {
      setCoordinates({ x: 0, y: 0 });
    });

    map.on('update', () => {
      setZoom(map.zoom || 1);
    });

    // Debug events
    map.on('mouse:down', (e: any) => {
      if (e && e.pointer) {
        console.log('mouse:down', e.pointer);
      }
    });

    map.on('mouse:up', (e: any) => {
      if (e && e.pointer) {
        console.log('mouse:up', e.pointer);
      }
    });

    map.on('mouse:dblclick', (e: any) => {
      if (e && e.pointer) {
        console.log('mouse:dblclick', e.pointer);
      }
    });
  }, []);

  const handleMinZoomChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseFloat(e.target.value);
    if (!isNaN(value) && value > 0) {
      setMinZoom(value);
      if (mapInstance) {
        mapInstance.minZoom = value;
        if (mapInstance.zoom < value) {
          mapInstance.setZoom(value);
        }
      }
    }
  }, [mapInstance]);

  const handleMaxZoomChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseFloat(e.target.value);
    if (!isNaN(value) && value > minZoom) {
      setMaxZoom(value);
      if (mapInstance) {
        mapInstance.maxZoom = value;
        if (mapInstance.zoom > value) {
          mapInstance.setZoom(value);
        }
      }
    }
  }, [mapInstance, minZoom]);

  const handleResetView = useCallback(() => {
    if (mapInstance && mapInstance.reset) {
      mapInstance.reset();
    }
  }, [mapInstance]);

  return (
    <DemoContainer>
      <h1>fabric-layers Grid Demo</h1>
      
      <Controls>
        <Label>
          Min Zoom:
          <Input
            type="number"
            step="0.01"
            value={minZoom}
            onChange={handleMinZoomChange}
          />
        </Label>
        
        <Label>
          Max Zoom:
          <Input
            type="number"
            step="0.01"
            value={maxZoom}
            onChange={handleMaxZoomChange}
          />
        </Label>
        
        <Button onClick={handleResetView}>
          Reset View
        </Button>
        
        <MonospaceText>
          X: {coordinates.x.toFixed(1)}, Y: {coordinates.y.toFixed(1)}
        </MonospaceText>
        
        <MonospaceText>
          Zoom: {zoom.toFixed(2)}x
        </MonospaceText>
      </Controls>

      <CanvasContainer>
        <Map
          width={800}
          height={600}
          onReady={handleMapReady}
          defaultMode="GRAB"
          minZoom={minZoom}
          maxZoom={maxZoom}
        >
          <Grid />
        </Map>
      </CanvasContainer>
    </DemoContainer>
  );
};

export default GridDemo;
